- name: design
  color: 4da6ff
  description: "Over All game design"
- name: programming
  color: b300b3
  description: "Coding and RenPy"
- name: docs
  color: 00ff55
  description: "Documentation change"
- name: wip
  color: 7057ff
  description: "Work in progress"
- name: bug
  color: d73a4a
  description: "something isn't working"
- name: help wanted
  color: 008672
  description: "Extra attention is needed"
- name: invalid
  color: e4e669
  description: "something isn't correct"
- name: question
  color: d876e3
  description: "more information is requested"
- name: wontfix
  color: ffffff
  description: "This will not be worked on"
- name: waiting
  color: 66066
  description: "Waiting on something to continue"
- name: gui
  color: 50E7C4
  description: User Interface related
- name: characters
  color: 97E750
  description: Character development
- name: story line
  color: EE88C1
  description: Story related
- name: renpy
  color: 	FF7F50
  description: RenPy language
- name: late
  color: EE1124
  description: Events running late on completion
- name: automation
  color: 8A2BE2
  description: automagical tooling
- name: duplicate
  color: fFF500
  description: duplicate issue already tracked
- name: web
  color: 008080
  description: website related
- name: graphics
  color: 00FFFF
  description: image/graphic related
- name: translation
  color: e5e5e5
  description: changes in translation files
- name: modile
  color: 56ff54
  description: mobile device related
- name: setting
  color: ec35aa
  description: the setting of the story line
