[book]
authors = ["Bytebuddha"]
language = "en"
multilingual = false
src = "src"
title = "Design Documentation"

[build]
build-dir = "../docs/design"

[output.html]
default-theme = "coal"
prefered-dark-theme = "coal"
