[book]
authors = ["Bytebuddha"]
language = "en"
multilingual = false
src = "src"
title = "Example Game Guide"

[build]
build-dir = "../docs/guide"

[output.html]
default-theme = "coal"
prefered-dark-theme = "coal"
