on:
  repository_dispatch:
    types: [deploy-command]

jobs:
  check_init_command:
    name: run deploy command
    runs-on: ubuntu-18.04
    steps:
        - name: Check out code
          uses: actions/checkout@master
        - name: Setup mdBook
          uses: peaceiris/actions-mdbook@v1
          with:
            mdbook-version: 'latest'

        - run: mdbook build guide
        - run: mdbook build design

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: docs/
