name: pull request linter

on:
  pull_request

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: Dreamcodeio/pr-has-label-action@master
      id: checkDocsLabel
      with:
        label: docs
    - uses: Dreamcodeio/pr-has-label-action@master
      id: checkDesignLabel
      with:
        label: design
    - uses: Dreamcodeio/pr-has-label-action@master
      id: checkRenPyLabel
      with:
        label: renpy
    - name: Does 'pull_request' has ${{ steps.checkDesignLabel.outputs.checkedLabel }} label?
      run: echo "${{ steps.checkDesignLabel.outputs.hasLabel }}"
    - name: Check out code
      uses: actions/checkout@master
    - name: Run mdl
      if: steps.checkDesignLabel.outputs.hasLabel || steps.checkDocsLabel.outputs.hasLabel
      uses: actionshub/markdownlint@master
    - name: Lint VN project
      if: steps.checkRenPyLabel.outputs.hasLabel
      uses: ProjectAliceDev/renpy-lint-action@master
      env:
        SDL_AUDIODRIVER: dummy
        SDL_VIDEODRIVER: dummy
