name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  programming:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["programming", "renpy", "python"]'
          labels: '["programming"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["design"]'
          labels: '["design"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["docs", "doc", "documentation"]'
          labels: '["docs"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["automation", "build automation", "github actions"]'
          labels: '["automation"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["website"]'
          labels: '["web"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["renpy"]'
          labels: '["renpy"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
